import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal: photoModal,
  magicLink,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
  magicLink: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {magicLink}
        {photoModal}
        <div className="flex items-center justify-center h-full w-full p-6 bg-orange-100 text-purple-900 text-opacity-70">
          {children}
        </div>
      </body>
    </html>
  );
}
